# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view\ErosionDilatationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *


class ErosionDilatationDialog(QDialog):

    def __init__(self, *args, **kwargs):
        super(ErosionDilatationDialog, self).__init__(*args, **kwargs)

        self.setObjectName("Dialog")
        self.resize(403, 309)
        self.verticalLayout = QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QGroupBox(self)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.radio_erosion = QRadioButton(self.groupBox)
        self.radio_erosion.setObjectName("radio_erosion")
        self.horizontalLayout_3.addWidget(self.radio_erosion)
        self.radio_dilatation = QRadioButton(self.groupBox)
        self.radio_dilatation.setObjectName("radio_dilatation")
        self.horizontalLayout_3.addWidget(self.radio_dilatation)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        spacerItem = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.radio_boule = QRadioButton(self.groupBox_2)
        self.radio_boule.setObjectName("radio_boule")
        self.horizontalLayout_2.addWidget(self.radio_boule)
        self.radio_carre = QRadioButton(self.groupBox_2)
        self.radio_carre.setObjectName("radio_carre")
        self.horizontalLayout_2.addWidget(self.radio_carre)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem2 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.formLayout = QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.label)
        self.dimension = QSpinBox(self.groupBox_2)
        self.dimension.setMinimum(1)
        self.dimension.setMaximum(100)
        self.dimension.setSingleStep(2)
        self.dimension.setObjectName("dimension")
        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.dimension)
        self.verticalLayout_2.addLayout(self.formLayout)
        spacerItem3 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.groupBox)
        self.buttonBox = QDialogButtonBox(self)
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Cancel|QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi()
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)
        self.dimension.valueChanged.connect(self.onSpinBoxValueChanged)
        QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        self.setWindowTitle(_translate("Dialog", "Options"))
        self.label_4.setText(_translate("Dialog", "Type d\'opération :"))
        self.radio_erosion.setText(_translate("Dialog", "Erosion"))
        self.radio_dilatation.setText(_translate("Dialog", "Dilatation"))
        self.groupBox_2.setTitle(_translate("Dialog", "Options d\'entrées"))
        self.label_2.setText(_translate("Dialog", "Type :"))
        self.radio_boule.setText(_translate("Dialog", "Boule"))
        self.radio_carre.setText(_translate("Dialog", "Carré"))
        self.label.setText(_translate("Dialog", "Dimension"))

    def onSpinBoxValueChanged(self):
        if self.dimension.value() %2 == 0:
            self.dimension.setValue(self.dimension.value()+1)

    def getValues(self):
        return self.radio_erosion.isChecked(), self.radio_boule.isChecked(), self.dimension
